### ISSUE TITLE
Wheres the jar file?

### ISSUE THREAD

**Issue by xbroak** [almosr/android-svg-code-render#70]
I don't see what i'm actually supposed to be executing?

**Comment by almosr** [comment]
Grab the release:

https://github.com/almosr/android-svg-code-render/releases

Most recent one is:

https://github.com/almosr/android-svg-code-render/releases/download/v1.3.1/android-svg-code-render_v1.3.1_03012016.zip

Execute this file from the archive: android-svg-code-render.jar
